version: "3"
services:

  mongo:
    image: mongo
    volumes:
      - ./mongoData:/data/db
    network_mode: host

  node:
    image: node:12.16.2
    user: "${UID}:${GID}"
    depends_on:
      - mongo
    volumes:
      - ./:/home/node/vertest/
      - /home/croquetteland/.ssh/:/home/node/vertest/.ssh/
    working_dir: /home/node/vertest/
    network_mode: host
    environment:
      - NODE_ENV=production
      - MONGO_HOST=127.0.0.1
      - MONGO_PORT=27017
    command: bash -c "npm install --only=prod && node app/index.js"